// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikemnhgrneagkcwewicp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZW1uaGdybmVhZ2tjd2V3aWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTczNzIsImV4cCI6MjA2NzQ5MzM3Mn0.XbCT-UbmK1FmNNWW6aLg5yyq3sgGLRRMWf2wZUXsDos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});